Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -60,6 +60,25 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
 
           script: |
+
+            echo "Checking Docker installation..."
+
+            if ! command -v docker &> /dev/null
+            then
+                echo "Docker not found. Installing Docker..."
+
+                sudo apt update
+                sudo apt install -y docker.io
+
+                sudo systemctl start docker
+                sudo systemctl enable docker
+
+                sudo usermod -aG docker $USER
+            else
+                echo "Docker already installed"
+            fi
+            
+            echo "Pull latest image..."
             docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-web-app:latest
 
             docker stop cicd-web-app || true
